In [1]:
import numpy as np
from mp_api.client import MPRester
from pymatgen.core.operations import SymmOp
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
from pymatgen.electronic_structure.plotter import BSPlotter
from pymatgen.phonon.plotter import PhononBSPlotter
from jupyter_jsmol.pymatgen import quick_view
from lmapr1492 import plot_brillouin_zone, get_plot_bs, get_plot_dos, get_plot_bs_and_dos, get_branch_wavevectors
from plotly.subplots import make_subplots
import plotly.graph_objects as go

In [2]:
with MPRester("kMkuaNd0F7org0EE2QryQaonTKfVvGw4") as m:
    structure = m.get_structure_by_material_id("mp-10226")
struct = SpacegroupAnalyzer(structure)
struct_con = struct.get_conventional_standard_structure()
struct_analyze = SpacegroupAnalyzer(struct_con)

Retrieving MaterialsDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

In [3]:
view = quick_view(struct_con,supercell=[1,1,1])
display(view)

JsmolView(layout=Layout(align_self='stretch', height='400px'))

In [90]:
sym = SpacegroupAnalyzer(structure).get_symmetry_operations()

# Symétries choisies pour les atomes
# inversion (-x;-y;-z)
S1 = sym[2]
# roto-inversion
S2 = sym[14]
# roto-réflexion
S3 = sym[16]

# Atomes choisis
Na = [0.0, 1.0, 0.0]
Y = [1.0, 0.0, 0.5]
S = [0.0, 0.0, 0.25]

# Application des symétries
Na_sym = S1.operate(Na)
Y_sym = S2.operate(Y)
S_sym = S3.operate(S)

In [91]:
print("Opération de symétrie 1: \n")
print("L'atome de départ est le Na et a comme coordonnées: {}\n".format(Na))
print("On lui applique une symétrie de centre 0 (inversion):\n")
print(S1.rotation_matrix, "*", Na, '+', S1.translation_vector)
print("L'atome d'arrivé a comme coordonnées : {}\n".format(Na_sym))


Opération de symétrie 1: 

L'atome de départ est le Na et a comme coordonnées: [0.0, 1.0, 0.0]

On lui applique une symétrie de centre 0 (inversion):

[[-1.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0. -1.]] * [0.0, 1.0, 0.0] + [0. 0. 0.]
L'atome d'arrivé a comme coordonnées : [ 0. -1.  0.]



In [94]:
print("Opération de symétrie 2: \n")
print("L'atome de départ est l'Y et a comme coordonnées: {}\n".format(Y))
print("On lui applique une roto-inversion (z,y,x) :")
print(S2.rotation_matrix, "*", Y, '+', S2.translation_vector)
print("L'atome d'arrivé a comme coordonnées : {}\n".format(Y_sym))


Opération de symétrie 2: 

L'atome de départ est l'Y et a comme coordonnées: [1.0, 0.0, 0.5]

On lui applique une roto-inversion (z,y,x) :
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]] * [1.0, 0.0, 0.5] + [0. 0. 0.]
L'atome d'arrivé a comme coordonnées : [0.5 0.  1. ]



In [96]:
print("Opération de symétrie 3: \n")
print("L'atome de départ est le S et a comme coordonnées: {}\n".format(S))
print("On lui applique une roto-réflexion (-x,-z,-y) : ")
print(S3.rotation_matrix, "*", S, '+', S3.translation_vector)
print("L'atome d'arrivé a comme coordonnées : {}\n".format(S_sym))


Opération de symétrie 3: 

L'atome de départ est le S et a comme coordonnées: [0.0, 0.0, 0.25]

On lui applique une roto-réflexion (-x,-z,-y) : 
[[-1.  0.  0.]
 [ 0.  0. -1.]
 [ 0. -1.  0.]] * [0.0, 0.0, 0.25] + [0. 0. 0.]
L'atome d'arrivé a comme coordonnées : [ 0.   -0.25  0.  ]

