In [1]:
import numpy as np
from mp_api.client import MPRester
from pymatgen.core.operations import SymmOp
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
from pymatgen.electronic_structure.plotter import BSPlotter
from pymatgen.phonon.plotter import PhononBSPlotter
from jupyter_jsmol.pymatgen import quick_view
from lmapr1492 import plot_brillouin_zone, get_plot_bs, get_plot_dos, get_plot_bs_and_dos, get_branch_wavevectors
from plotly.subplots import make_subplots
import plotly.graph_objects as go

In [2]:
with MPRester("kMkuaNd0F7org0EE2QryQaonTKfVvGw4") as m:
    structure = m.get_structure_by_material_id("mp-30847")
struct = SpacegroupAnalyzer(structure)
struct_con = struct.get_conventional_standard_structure()
struct_analyze = SpacegroupAnalyzer(struct_con)

Retrieving MaterialsDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

In [3]:
view = quick_view(struct_con,supercell=[1,1,1])
display(view)

JsmolView(layout=Layout(align_self='stretch', height='400px'))

In [10]:
sym = SpacegroupAnalyzer(structure).get_symmetry_operations()

# Symétries choisies pour les atomes
# Plan miroir (z,y,x)
S1 = sym[7]
# Axe 4-barre | centre d'inversion en (0,0,0)  (-x-y-z,x,y)
S2 = sym[3]
# Axe de rotation C2 (y,x,-x-y-z)
S3 = sym[6]

# Atomes choisis
Ti = [0.0, 0.0, 0.0]
Sn = [0.5, 0.5, 0.5]
Pt = [0.25, 0.25, 0.75]

# Application des symétries
Ti_sym = S1.operate(Ti)
Sn_sym = S2.operate(Sn)
Pt_sym = S3.operate(Pt)

In [12]:
print("Opération de symétrie 1: \n")
print("L'atome de départ est le Ti et a comme coordonnées: {}\n".format(Ti))
print("On lui applique une symétrie de plan miroir (z,y,x) :\n")
print(S1.rotation_matrix, "*", Ti, '+', S1.translation_vector)
print("L'atome d'arrivé a comme coordonnées : {}\n".format(Ti_sym))
v1 = quick_view(structure)
display(v1)
v1.script("draw symop 8 {atomno=1}")

Opération de symétrie 1: 

L'atome de départ est le Ti et a comme coordonnées: [0.0, 0.0, 0.0]

On lui applique une symétrie de plan miroir (z,y,x) :

[[-1. -1. -1.]
 [ 1.  0.  0.]
 [ 0.  1.  0.]] * [0.0, 0.0, 0.0] + [0. 0. 0.]
L'atome d'arrivé a comme coordonnées : [0. 0. 0.]



JsmolView(layout=Layout(align_self='stretch', height='400px'))

In [13]:
print("Opération de symétrie 2: \n")
print("L'atome de départ est le Sn et a comme coordonnées: {}\n".format(Sn))
print("On lui applique une roto-inversion (-x-y-z,x,y) :")
print(S2.rotation_matrix, "*", Sn, '+', S2.translation_vector)
print("L'atome d'arrivé a comme coordonnées : {}\n".format(Sn_sym))
v1 = quick_view(structure)
display(v1)
v1.script("draw symop 4 {atomno=7}")

Opération de symétrie 2: 

L'atome de départ est le Sn et a comme coordonnées: [0.5, 0.5, 0.5]

On lui applique une roto-inversion (-x-y-z,x,y) :
[[ 0.  1.  0.]
 [ 0.  0.  1.]
 [-1. -1. -1.]] * [0.5, 0.5, 0.5] + [0. 0. 0.]
L'atome d'arrivé a comme coordonnées : [ 0.5  0.5 -1.5]



JsmolView(layout=Layout(align_self='stretch', height='400px'))

In [14]:
print("Opération de symétrie 3: \n")
print("L'atome de départ est le Pt et a comme coordonnées: {}\n".format(Pt))
print("On lui applique une symétrie d'axe 2 (y,x,-x-y-z) : ")
print(S3.rotation_matrix, "*", Pt, '+', S3.translation_vector)
print("L'atome d'arrivé a comme coordonnées : {}\n".format(Pt_sym))
v1 = quick_view(structure)
display(v1)
v1.script("draw symop 7 {atomno=3}")

Opération de symétrie 3: 

L'atome de départ est le Pt et a comme coordonnées: [0.25, 0.25, 0.75]

On lui applique une symétrie d'axe 2 (y,x,-x-y-z) : 
[[-1. -1. -1.]
 [ 1.  0.  0.]
 [ 0.  1.  0.]] * [0.25, 0.25, 0.75] + [0. 0. 0.]
L'atome d'arrivé a comme coordonnées : [-1.25  0.25  0.25]



JsmolView(layout=Layout(align_self='stretch', height='400px'))